### ISSUE TITLE
no models 

### ISSUE THREAD

**Issue by dpramirez** [ujjwalsharma9/Fire-Detection#1]
Where do I get the smokes_inference_graph_v1.pb and frozen_inference_graph.pb? Models, every time I try to run the real_det.py I'm told not to find them. regards

**Comment by ujjwalsharma9** [comment]
Hello

You have to follow the steps given on the site (https://tensorflow-object-detection-api-tutorial.readthedocs.io/en/latest/training.html) with labeled fire and smoke datasets. The inference graphs are created as a result of training and further used to detect the required objects.
